@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "MainClass",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1003854516 { 
   	label=PaymentProcessor
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   PaymentProcessor1003854516[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PaymentProcessor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   getInput: GetInput [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sc: Scanner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   theCart: Cart [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   theLogger: Logger [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ finalizeOrder()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1206283898 { 
   	label=CartContents
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CartContents1206283898[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CartContents</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cartItems: ArrayList&lt;Product&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cartSize: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cartVariety: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isSaleReady: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prodFact: ProductFactory [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addToCart(prod: Product, n: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getItem(n: int): Product</TD></TR>
<TR><TD ALIGN="LEFT" >+ printProdList()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeFromCart(prod: Product, n: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1355179215 { 
   	label=Product
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Product1355179215[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Product</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   price: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prodID: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productNum: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   qty: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   type: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1471215356 { 
   	label=OrderProcessor
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   OrderProcessor1471215356[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderProcessor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   catalog: Catalog [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   getInput: GetInput [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   menuLength: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sc: Scanner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usersCart: CartContents [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addCartContents()</TD></TR>
<TR><TD ALIGN="LEFT" >+ printMenu()</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeCartContents()</TD></TR>
<TR><TD ALIGN="LEFT" >+ shop(): CartContents</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1726840607 { 
   	label=MainClass
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   MainClass1726840607[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainClass</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1774187813 { 
   	label=ClothingItem
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ClothingItem1774187813[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClothingItem</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1969169858 { 
   	label=UserLogin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   UserLogin1969169858[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserLogin</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   credsFile: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   credsMap: HashMap&lt;String, String&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custAddr: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custCardNum: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custCardType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   getInput: GetInput [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   newUser: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sc: Scanner [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   theCatalog: Catalog [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   theLogger: Logger [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- loadSavedCreds(): HashMap&lt;String, String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ loadUserCart(): CartContents</TD></TR>
<TR><TD ALIGN="LEFT" >- loadUserInfo()</TD></TR>
<TR><TD ALIGN="LEFT" >+ logIn(): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2013470288 { 
   	label=Logger
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Logger2013470288[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Logger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createLogger(): Logger</TD></TR>
<TR><TD ALIGN="LEFT" >+ logEvent(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ logUserOrder(theCart: Cart)</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveCredentials(credsFile: String, credsMap: HashMap&lt;String, String&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveUserCart(custName: String, cartItems: CartContents)</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveUserInfo(custName: String, custAddr: String, custCardType: String, custCardNum: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2020827700 { 
   	label=GetInput
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   GetInput2020827700[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GetInput</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   sc: Scanner [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fillInRequiredInfo(theCart: Cart)</TD></TR>
<TR><TD ALIGN="LEFT" >+ userIndicatesQty(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ userSaysY_N(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ userSaysY_N_E(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ userSelectsChoice(numChoices: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ userSelectsItem(pl: ProductList): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2067279163 { 
   	label=ProductFactory
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ProductFactory2067279163[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ProductFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createProduct(type: String, name: String, price: double, prodID: int): Product</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2074609671 { 
   	label=Catalog
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Catalog2074609671[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Catalog</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   catalogItems: ArrayList&lt;Product&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prodFact: ProductFactory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   size: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getItem(itemNo: int): Product</TD></TR>
<TR><TD ALIGN="LEFT" >+ printProdList()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2092864 { 
   	label=Cart
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Cart2092864[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cart</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cartItems: CartContents [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custAddr: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custCardNum: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custCardType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ clearCartContents()</TD></TR>
<TR><TD ALIGN="LEFT" >- createCart(builder: CartBuilder): Cart</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CartBuilder2092864[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CartBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cartItems: CartContents [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custAddr: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custCardNum: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custCardType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   custName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ build(): Cart</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCartItems(cartItems: CartContents): CartBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCustAddr(addr: String): CartBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCustCardNum(cardNum: int): CartBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCustCardType(cardType: String): CartBuilder</TD></TR>
<TR><TD ALIGN="LEFT" >+ setCustName(custName: String): CartBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_654823931 { 
   	label=FurnitureItem
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   FurnitureItem654823931[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FurnitureItem</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_839668128 { 
   	label=GroceryItem
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   GroceryItem839668128[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GroceryItem</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Cart2092864 -> CartContents1206283898[label="cartItems
[0..1]"];
CartBuilder2092864 -> Cart2092864[label="build() -> createCart()"];
CartBuilder2092864 -> CartContents1206283898[label="cartItems
[0..1]"];
CartContents1206283898 -> Catalog2074609671[arrowhead=none];
CartContents1206283898 -> Product1355179215[label="cartItems
[0..1]"];
CartContents1206283898 -> ProductFactory2067279163[label="prodFact
[0..1]"];
Catalog2074609671 -> Product1355179215[label="catalogItems
[0..1]"];
Catalog2074609671 -> ProductFactory2067279163[label="prodFact
[0..1]"];
MainClass1726840607 -> OrderProcessor1471215356[label="main() -> shop()"];
MainClass1726840607 -> PaymentProcessor1003854516[label="main() -> finalizeOrder()"];
OrderProcessor1471215356 -> CartContents1206283898[label="usersCart
[0..1]"];
OrderProcessor1471215356 -> Catalog2074609671[label="catalog
[0..1]"];
OrderProcessor1471215356 -> GetInput2020827700[label="getInput
[0..1]"];
PaymentProcessor1003854516 -> Cart2092864[label="theCart
[0..1]"];
PaymentProcessor1003854516 -> GetInput2020827700[label="getInput
[0..1]"];
PaymentProcessor1003854516 -> Logger2013470288[label="theLogger
[0..1]"];
Product1355179215 -> ClothingItem1774187813[arrowhead=none, arrowtail=empty, dir=both];
Product1355179215 -> FurnitureItem654823931[arrowhead=none, arrowtail=empty, dir=both];
Product1355179215 -> GroceryItem839668128[arrowhead=none, arrowtail=empty, dir=both];
UserLogin1969169858 -> CartContents1206283898[label="loadUserCart() -> addToCart()"];
UserLogin1969169858 -> Catalog2074609671[label="theCatalog
[0..1]"];
UserLogin1969169858 -> GetInput2020827700[label="getInput
[0..1]"];
UserLogin1969169858 -> Logger2013470288[label="theLogger
[0..1]"];
    
}
@enduml